name: Discord Notification

on:
  push:
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Send Discord notification
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
        title: "New commit to main"
        description: |
          **Repository:** ${{ github.repository }}
          **Commit:** [`${{ github.event.head_commit.id }}`](${{ github.event.head_commit.url }})
          **Author:** ${{ github.event.head_commit.author.name }}
          **Message:** ${{ github.event.head_commit.message }}
        color: 0x00ff00